### PR TITLE
Add support for configuring GCP Credentials as json (from env variable)

### PR DESCRIPTION
**Pull request by pradeeppattamatta**
Changes to add this feature - https://github.com/benthosdev/benthos/issues/1761

Please Refer #1831 for history of conversations.

Creating a new PR since the past commits were not signed off and I had trouble to go back and update the commits.

### CODE REVIEW

**Comment by pradeeppattamatta** [comment]
@Jeffail Can you please check this PR now.

Note: Please Refer https://github.com/benthosdev/benthos/pull/1831 for history of conversations.

Creating a new PR since the past commits were not signed off and I had trouble to go back and update the commits.

**Comment by pradeeppattamatta** [comment]
Hi @Jeffailcan you pls check on this PR. Let me know if you feel this needs any more change and we can discuss further

**Comment by mihaitodor** [comment]
I think #2759 should cover this functionality. Sorry it took so long to get to it...

**Comment by pradeeppattamatta** [comment]
Thanks @mihaitodor.

**Comment by mihaitodor** [comment]
You're welcome! The changes were released in [v4.33.0](https://github.com/redpanda-data/connect/releases/tag/v4.33.0). Please feel free to open a new issue if you need any other enhancements.

**Pull request closed without merging**
