### PR TITLE
Update bundled packages to the latest Connect and Benthos versions

### LINKED ISSUE #2905: Bump bundled version to latest release (v4.47.0)
Currently both [free](https://github.com/redpanda-data/connect/blob/main/public/bundle/free/go.mod) and [enterprise](https://github.com/redpanda-data/connect/blob/main/public/bundle/enterprise/go.mod) are on v4.31.0, requiring the use for `replace` when writing plugins that target the newer versions (https://github.com/united-manufacturing-hub/benthos-umh/pull/63/files).

### PR DESCRIPTION
**Pull request by mihaitodor**
Fixes #2905.

### CODE REVIEW

**Review by rockwotj — APPROVED** [review]
We should really automate this one - can dependabot or renovate do this?

**Comment by mihaitodor** [comment]
@rockwotj Good question... I guess we can do a preflight check before tagging a new release. It's a bit like a chicken before the egg issue, since you can't both bump the version and, also, modify these files as part of the same commit. Curious if you have any ideas on how to approach it.

**Comment by rockwotj** [comment]
Ah these are incremented in the same "tag", they are separate tags/release: https://github.com/redpanda-data/connect/releases/tag/public%2Fbundle%2Fenterprise%2Fv4.31.0

So we can: release, open PR to bump, then separately release the bundles

**Comment by rockwotj** [comment]
cc: @Jeffail

**Pull request merged**
