### PR TITLE
Support Sep (%2F) workaround in Schema Registry Processors

### PR DESCRIPTION
**Pull request by Mizaro**
I added a file for integration test and tests to the client.go. 
This is a very pinpoint fix and maybe someone can help me find a better location in the code.

### CODE REVIEW

**Comment by Mizaro** [comment]
This is still a WIP related to https://github.com/benthosdev/benthos/issues/2584 
I hope to continue soon

**Comment by Mizaro** [comment]
Ready for Review

**Comment by Jeffail** [comment]
https://pkg.go.dev/net/url#URL

**Review by Jeffail — APPROVED** [review]
LGTM, thanks @Mizaro. I've rebased your changes and fixed all of the linting errors so we're good to go. Are you happy to sign the CLA?

**Comment by Mizaro** [comment]
@Jeffail I signed it

**Comment by Jeffail** [comment]
Awesome, thanks @Mizaro!

**Pull request merged**
