### PR TITLE
Parallelize docker releases using matrix

### PR DESCRIPTION
**Pull request by rockwotj**
See documentation here: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow

### CODE REVIEW

**Comment by jackietung-redpanda** [comment]
This is awesome!  I also just noticed the multiple, slow serial steps.  In future, if we want it even faster, we can use larger instances, or use something like depot.dev.

**Comment by rockwotj** [comment]
I think after we'll probably be good for a while, but larger instances might be nice. It only takes be a couple minutes to build an image locally with 12 cores.

**Comment by rockwotj** [comment]
BTW I tested that this expands to the right set of variables here: https://github.com/rockwotj/redpanda-connect/actions/runs/10728166709

(The job fails because there are secrets not set, but that's expected)

**Review by Jeffail — APPROVED** [review]
Awesome, thanks @rockwotj!

**Pull request merged**
