### PR TITLE
Rename to Redpanda Connect

### PR DESCRIPTION
**Pull request by Jeffail**
Renames the project and moves Benthos out as a core engine dependency to https://github.com/redpanda-data/benthos

### CODE REVIEW

**Comment by emaxerrno** [comment]
let's go! 🚀

**Comment by vordimous** [comment]
Congrats @Jeffail! Redpanda is an awesome company and Benthos is an amazing project. I hope they continue all of the great work you have done.

**Comment by mxcoder** [comment]
Congratulations @Jeffail !

**Comment by danriedl** [comment]
Ayyy lmao ledds goo
image

**Pull request merged**
